// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MK6.MicroServices.ReportTemplates {

  /// <summary>Holder for reflection information generated from service.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class ServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1zZXJ2aWNlLnByb3RvEiFNSzYuTWljcm9TZXJ2aWNlcy5SZXBvcnRUZW1w",
            "bGF0ZXMaDm1lc3NhZ2VzLnByb3RvMpgBChVSZXBvcnRUZW1wbGF0ZVNlcnZp",
            "Y2USfwoQR2V0UmVwb3J0Rm9sZGVycxI2Lk1LNi5NaWNyb1NlcnZpY2VzLlJl",
            "cG9ydFRlbXBsYXRlcy5SZXBvcnRGb2xkZXJSZXF1ZXN0Gi8uTUs2Lk1pY3Jv",
            "U2VydmljZXMuUmVwb3J0VGVtcGxhdGVzLlJlcG9ydEZvbGRlciIAMAFiBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::MK6.MicroServices.ReportTemplates.MessagesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
